### ISSUE TITLE
Unexpected output in console

### ISSUE THREAD

**Issue by harshh3010** [iqans/flutter-paytm-webview#2]
### Describing the issue

In the following statements, the expected output is not being printed

https://github.com/iqans/flutter-paytm-webview/blob/100fce21e82a4c88bea6e1944b7b3c484b4ad8c7/lib/payment.dart#L56-L60

You may notice that the entire cookie object gets printed in the console everytime, this is due to the missing braces which should be used along with cookie parameters.

### Correction

 print('TXNID ${cookies["TXNID"]}'); would return the expected output

PS : Your work is just amazinggg!! 😀 It helped me a lott...

**Comment by iqan** [comment]
Thanks for noticing that and opening an issue. It's fixed now.
Glad to know it helped 👍Cheers!
